#!/bin/bash

# Update the package repository
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create HTML directory and index.html file
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html

# Create Nginx configuration for redirection
sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

