#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

# Use sudo to execute commands as root
sudo apt-get update
sudo apt-get install -y nginx


sudo mkdir -p /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html > /dev/null


sudo bash -c 'cat > /etc/nginx/sites-available/default' <<EOL
server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

sudo service nginx restart

