#!/usr/bin/env bash
# configure ufw to block all incoming traffic except for TCP of ports 80, 443, and 22

sudo apt update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status
~                   
