#!/usr/bin/env/ bash
# SSH client configuration

Host *
passwordAuthenticatioin no
IdentityFile ~/.ssh/school
SendEnv LANG LC_*
HashKnownHosts yes
GSSAPIAuthentication yes
GSSAPIDelegateCredentials no

